### ISSUE TITLE
"fatal: could not create leading directories of '/home/odoo/pyenv': Permission denied"

### ISSUE THREAD

**Issue by dpthegrey** [coopdevs/odoo-role#103]
I am using this ansible odoo-role, when I ran the playbook from my local ansible master to remote linux 18.04 node.

this is the task where I am getting error running as a odoo user but the task also has become: yes and then we are trying to do `become_user: "{{ odoo_role_odoo_user }}"` is that why we are getting this error?
![Screenshot 2021-02-16 at 16 31 28](https://user-images.githubusercontent.com/49444980/108054837-2f2e9a80-7075-11eb-8a3c-24f198add715.png)
the task is at https://github.com/coopdevs/odoo-role/blob/master/tasks/pyenv.yml#L30

asked the same question on stackoverflow before creating a issue here. Kindly check it out if you would like to answer. Thanks
https://stackoverflow.com/questions/66222672/fatal-could-not-create-leading-directories-of-home-odoo-pyenv-permission-d

**Comment by enricostano** [comment]
Hi @dpthegrey ! Would you mind to run the playbook with `-vv` verbose output and post here the more verbose error output of that task? Thanks!

**Comment by raneq** [comment]
> could not create leading directories of '/home/odoo/pyenv': Permission denied"

I understand from this that it's trying to create `/home/odoo/pyenv` but that `/home/odoo/` doesn't exist yet.
odoo-role should have created that directory when creating the odoo user, as "create_home" defaults to "yes" (see [ansible docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html?highlight=create_home#parameter-create_home))

The role could make this explicit, if needed, with:
```yml
user:
...
  create_home: yes
  home: "/home/{{ odoo_role_odoo_user }}"
```
at https://github.com/coopdevs/odoo-role/blob/v0.2.19/tasks/create-user.yml#L8

However, it's strange that the directory is not there.

**Comment by danypr92** [comment]
Hi @dpthegrey! Any new about this problem? Could you fix it?

**Comment by dpthegrey** [comment]
Hey @danypr92 @enricostano Sorry for responding late I've lost the track of the issue. I found a [bash script](https://github.com/Yenthe666/InstallScript) which got the job done at that time so I went ahead with that and couldn't fix the problem.
Now, to reproduce the error again I would have to run it again. 

> However, it's strange that the directory is not there.

@raneq I couldn't recall if I've changed the user to other than ooo as [mentioned here](https://github.com/coopdevs/odoo-role/blob/master/defaults/main.yml#L3) (probably not changed) but I assume this could be related to [L31](https://github.com/coopdevs/odoo-role/blob/master/tasks/pyenv.yml#L31) & [L32](https://github.com/coopdevs/odoo-role/blob/master/tasks/pyenv.yml#L32) with the root user and odoo user's permission priority while trying to install the package. Could that be possible?

**Comment by enricostano** [comment]
@raneq @dpthegrey can we close this issue?

**Comment by enricostano** [comment]
Sorry... I didn't mean to close it...

**Comment by dpthegrey** [comment]
Hey @enricostano no worries, yes I think we can close the issue. As @raneq mentions, the playbook should create a odoo user and should work fine with given permissions. However, I haven't tried reproducing the same error.
