### ISSUE TITLE
Change `Administrator` user password

### ISSUE THREAD

**Issue by danypr92** [coopdevs/odoo-role#12]
After run `--init` execute a command to change de Administrator user database

**Comment by enricostano** [comment]
We found this script: https://github.com/jesusdanielcf/OdooUserPassChanger

But I guess we need a better solution. Or at least integrate it in our workflow somehow.

**Comment by enricostano** [comment]
@danypr92 is this still valid?

**Comment by raneq** [comment]
We still haven't implemented a way to change admin user automatically. Still doing it by hand after first provision.

**Comment by enricostano** [comment]
Probably, we shouldn't do it automatically. If we change the administrator pwd and we provision again we would end up with a mess. I would close this issue.
