### ISSUE TITLE
Install Python setuptools package 

### ISSUE THREAD

**Issue by danypr92** [coopdevs/odoo-role#32]
To install the `requirements.txt` downloaded with the OCA/OCB repository is needed the `python-setuptools` package. 

https://github.com/coopdevs/odoo-role/blob/1096c17c12c6296f00796319a2561932b2993fe4/tasks/main.yml#L10

**Comment by enricostano** [comment]
This will be fixed by #34 , right?

**Comment by danypr92** [comment]
Closed by #34
