### ISSUE TITLE
Move this repository to Gitlab

### ISSUE THREAD

**Issue by danypr92** [coopdevs/odoo-role#39]
I propose to move this repository to Gitlab.

We can create a pull mirror in Gitlab and keep working in this repository to solve the issues of this repository. When this board will be clean, we can start to work in Gitlab and change the Gitlab mirror from pull to push mirror.

Documentation: https://docs.gitlab.com/ee/workflow/repository_mirroring.html#pulling-from-a-remote-repository

**Comment by danypr92** [comment]
I create a mirror in my personal projects:

https://gitlab.com/danypr92/github-mirror/edit#js-general-project-settings

**Comment by enricostano** [comment]
I would just import the repo to GitLab and archive it in GitHub:

https://gitlab.com/import/github/new

**Comment by danypr92** [comment]
Yes, we can do it and update the link in Galaxy to point to the new Gitlab repository. :muscle:

**Comment by enricostano** [comment]
We decided to leave it in GH
